/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLARATION = 1;
  public int JJTNORMALDECLARATION = 2;
  public int JJTLISTDECLARATION = 3;
  public int JJTBLOCK = 4;
  public int JJTSTMT = 5;
  public int JJTFORSTMT = 6;
  public int JJTFOREACHSTMT = 7;
  public int JJTIFSTMT = 8;
  public int JJTWHILESTMT = 9;
  public int JJTASSIGNSTMT = 10;
  public int JJTEXPR = 11;
  public int JJTBOOLEXPR = 12;
  public int JJTCOMPEXPR = 13;
  public int JJTADDEXPR = 14;
  public int JJTMULEXPR = 15;
  public int JJTUNAEXPR = 16;
  public int JJTNOTEXPR = 17;
  public int JJTGENVALUE = 18;
  public int JJTBOOLVALUE = 19;
  public int JJTIDENTIFIER = 20;
  public int JJTINTVALUE = 21;
  public int JJTREALVALUE = 22;


  public String[] jjtNodeName = {
    "Program",
    "Declaration",
    "NormalDeclaration",
    "ListDeclaration",
    "Block",
    "Stmt",
    "ForStmt",
    "ForEachStmt",
    "IfStmt",
    "WhileStmt",
    "AssignStmt",
    "Expr",
    "BoolExpr",
    "CompExpr",
    "AddExpr",
    "MulExpr",
    "UnaExpr",
    "NotExpr",
    "GenValue",
    "BoolValue",
    "Identifier",
    "IntValue",
    "RealValue",
  };
}
/* JavaCC - OriginalChecksum=98d49bbdf45b9aa62fdf360152ef152c (do not edit this line) */
